### ISSUE TITLE
下载失败卡住

### ISSUE THREAD

**Issue by datouzhan** [izdbrave/BaiduMapDownload#1]
下载到百分之八十速度明显降低0b/s，大概隔10分钟下载一张

**Comment by izdbrave** [comment]
请提供下载参数

**Comment by datouzhan** [comment]
threads = 3000
path = ./tiles
ext = png
minLevel = 16
maxLevel = 19
leftTop = 113.415474,23.195422
rightBottom = 113.448568,23.17549
customid = midnight
style = ''

**Comment by izdbrave** [comment]
不算是个问题，因为有时候百度服务器很长时间没有响应，超时了会自动重试。

**Comment by datouzhan** [comment]
好的，了解。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "izdbrave"<notifications@github.com&gt;; 
发送时间: 2020年4月22日(星期三) 上午10:02
收件人: "izdbrave/BaiduMapDownload"<BaiduMapDownload@noreply.github.com&gt;; 
抄送: "Gypsophila"<2920356983@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [izdbrave/BaiduMapDownload] 下载失败卡住 (#1)





 
不算是个问题，因为有时候百度服务器很长时间没有响应，超时了会自动重试。
